#!/bin/bash

# Create preprocessing_env
conda create -n preprocessing_env -c bioconda -c conda-forge -c hcc lib-pod5 minimap2=2.28 dorado -y

# Create kraken2_env
conda create -n kraken2_env -c bioconda -c conda-forge kraken2 seqtk -y

# Create assembly_env
conda create -n assembly_env -c bioconda -c conda-forge flye canu hifiasm wtdbg paralleltask nextdenovo -y

# Create polishing_env
conda create -n polishing_env -c bioconda -c conda-forge -c nanoporetech medaka racon quast -y

# Create qc_env
conda create -n qc_env -c bioconda -c conda-forge nanoplot fastqc qualimap bcftools samtools -y

# Create illuminareads_env
conda create -n illuminareads_env -c bioconda -c conda-forge bwa pilon freebayes -y

# Create annotation_env
conda create -n annotation_env -c bioconda -c conda-forge snpeff -y

# Create mummer_env (requires manual install of bedtools and blast if needed)
conda create -n mummer_env -c bioconda -c conda-forge mummer -y

# Create base_env
conda create -n base_env -c conda-forge -c bioconda pandas openpyxl biopython fasta3 -y

echo "All environments created. If struggling with the installation of some tools, please install it manually using github. Don't forget to activate each one with: conda activate <env_name>"
